

services:
  selenium-hub:
    image: selenium/hub:4.20.0-20240423
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.20.0-20240423
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test-runner:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
